# Intelligent Video Test Monitor
# Waits for job to reach 95%, then analyzes result

param(
    [Parameter(Mandatory=$true)]
    [string]$JobId,
    
    [int]$CheckIntervalSec = 5,
    [int]$MaxIterations = 200
)

Write-Host "`n=== INTELLIGENT VIDEO TEST MONITOR ===" -ForegroundColor Magenta
Write-Host "Job ID: $JobId" -ForegroundColor Yellow
Write-Host "Checking every $CheckIntervalSec seconds (max $MaxIterations iterations)`n" -ForegroundColor Gray

$lastProgress = -1
$stuck95Count = 0

for ($i = 1; $i -le $MaxIterations; $i++) {
    Start-Sleep -Seconds $CheckIntervalSec
    
    $response = Invoke-RestMethod -Uri "http://localhost:8000/api/video/job/$JobId" -Method Get -ErrorAction SilentlyContinue
    if (!$response) {
        Write-Host "[$i] Error checking status" -ForegroundColor Red
        continue
    }
    
    $state = $response.data.state
    $progress = $response.data.progress
    
    $color = if ($state -eq 'completed') { 'Green' } elseif ($state -eq 'failed') { 'Red' } elseif ($progress -ge 95) { 'Yellow' } else { 'Cyan' }
    $timestamp = Get-Date -Format "HH:mm:ss"
    
    Write-Host "[$timestamp] Iteration $i - Progress: $progress% | State: $state" -ForegroundColor $color
    
    # Check if progress changed
    if ($progress -eq $lastProgress) {
        Write-Host "  Progress unchanged (same as last check)" -ForegroundColor Yellow
    }
    $lastProgress = $progress
    
    # CRITICAL: Check when reaching 95%
    if ($progress -ge 95 -and $progress -lt 100) {
        $stuck95Count++
        Write-Host "`nJOB AT 95%+ - CRITICAL CHECKPOINT!" -ForegroundColor Yellow
        Write-Host "This is where Firebase upload should happen!" -ForegroundColor Yellow
        Write-Host "Check backend console for debug logs" -ForegroundColor Cyan
        
        if ($stuck95Count -ge 3) {
            Write-Host "Job stuck at 95% for 3+ checks!" -ForegroundColor Red
            Write-Host "This suggests Firebase upload is failing" -ForegroundColor Red
        }
    }
    
    # Check if completed
    if ($state -eq 'completed') {
        Write-Host "`n=== JOB COMPLETED ===" -ForegroundColor Green
        Write-Host "`nANALYZING RESULT...`n" -ForegroundColor Magenta
        
        if ($response.data.result) {
            $resultKeys = $response.data.result.PSObject.Properties.Name
            Write-Host "Result Keys: $($resultKeys -join ', ')" -ForegroundColor White
            
            # Check for success indicators
            $hasVideoUrl = $null -ne $response.data.result.videoUrl
            $hasStorageError = $null -ne $response.data.result.storageError
            
            Write-Host "`nSUCCESS CRITERIA:" -ForegroundColor Cyan
            Write-Host "  Job completed: YES" -ForegroundColor Green
            Write-Host "  Result exists: YES" -ForegroundColor Green
            
            if ($hasVideoUrl) {
                Write-Host "  Video URL exists: YES" -ForegroundColor Green
                Write-Host "    URL: $($response.data.result.videoUrl)" -ForegroundColor White
            } else {
                Write-Host "  Video URL exists: NO" -ForegroundColor Red
            }
            
            if ($hasStorageError) {
                Write-Host "  No storage errors: NO (ERROR FOUND!)" -ForegroundColor Red
                Write-Host "    Error: $($response.data.result.storageError)" -ForegroundColor White
            } else {
                Write-Host "  No storage errors: YES" -ForegroundColor Green
            }
            
            # Overall verdict
            if ($hasVideoUrl -and !$hasStorageError) {
                Write-Host "`nTEST PASSED - All fixes working correctly!" -ForegroundColor Green
                Write-Host "Video was successfully:" -ForegroundColor Green
                Write-Host "  1. Generated by ComfyUI" -ForegroundColor Green
                Write-Host "  2. Retrieved as Buffer" -ForegroundColor Green
                Write-Host "  3. Unwrapped from nested result" -ForegroundColor Green
                Write-Host "  4. Uploaded to Firebase Storage" -ForegroundColor Green
                Write-Host "  5. URL returned to frontend" -ForegroundColor Green
            } else {
                Write-Host "`nTEST FAILED - Issues remain" -ForegroundColor Red
                if (!$hasVideoUrl) {
                    Write-Host "  Missing video URL - upload likely failed" -ForegroundColor Red
                }
                if ($hasStorageError) {
                    Write-Host "  Storage error present - Firebase upload failed" -ForegroundColor Red
                }
            }
            
            # Full result
            Write-Host "`nFull Result Object:" -ForegroundColor Cyan
            $response.data.result | ConvertTo-Json -Depth 3 | Write-Host -ForegroundColor Gray
            
        } else {
            Write-Host "NO RESULT OBJECT!" -ForegroundColor Red
            Write-Host "Job completed but result was not saved" -ForegroundColor Red
            Write-Host "Check MockQueue.processJob() in queueService.js" -ForegroundColor Yellow
        }
        
        Write-Host ""
        break
    }
    
    # Check if failed
    if ($state -eq 'failed') {
        Write-Host "`nJOB FAILED!" -ForegroundColor Red
        if ($response.data.error) {
            Write-Host "Error: $($response.data.error)" -ForegroundColor White
        }
        if ($response.data.result -and $response.data.result.storageError) {
            Write-Host "Storage Error: $($response.data.result.storageError)" -ForegroundColor White
        }
        Write-Host ""
        break
    }
}

if ($i -gt $MaxIterations) {
    Write-Host "`nTIMEOUT - Max iterations reached" -ForegroundColor Yellow
    Write-Host "Job still processing after $($MaxIterations * $CheckIntervalSec) seconds" -ForegroundColor Yellow
}

Write-Host "`nMonitor finished`n" -ForegroundColor Green
