/**
 * Shot List Constants for Step5Output
 * Dropdown options for shot planning and storyboarding
 */

export const SHOT_OPTIONS: Record<string, string[]> = {
  shotSize: [
    'Select...',
    'ECU (Extreme Close Up)',
    'CU (Close Up)',
    'MCU (Medium Close Up)',
    'MS (Medium Shot)',
    'MLS (Medium Long Shot)',
    'LS (Long Shot)',
    'VLS (Very Long Shot)',
    'EST (Establishing Shot)',
  ],
  perspective: [
    'Select...',
    'Eye-Level',
    'High Angle',
    'Low Angle',
    "Bird's Eye / Overhead",
    "Worm's Eye",
    'POV (Point of View)',
    'OTS (Over the Shoulder)',
    'Canted / Dutch Angle',
    'Ground Level',
  ],
  movement: [
    'Select...',
    'Static',
    'Pan',
    'Tilt',
    'Dolly In',
    'Dolly Out',
    'Zoom In',
    'Zoom Out',
    'Tracking / Truck',
    'Crab',
    'Pedestal',
    'Crane / Jib',
    'Handheld',
    'Steadicam',
    'Gimbal / Stabilizer',
    'Arc',
    'Whip Pan',
  ],
  equipment: [
    'Select...',
    'Tripod',
    'Dolly',
    'Slider',
    'Jib / Crane',
    'Steadicam',
    'Gimbal (Ronin/Movi)',
    'Handheld Rig',
    'EasyRig',
    'Drone',
    'Snorricam',
    'Vehicle Mount',
  ],
  focalLength: [
    'Select...',
    '14mm (Ultra Wide)',
    '24mm (Wide)',
    '35mm (Standard Wide)',
    '50mm (Standard)',
    '85mm (Portrait)',
    '100mm (Macro/Tele)',
    '135mm (Telephoto)',
    '200mm+ (Super Tele)',
    'Zoom Lens',
  ],
  aspectRatio: [
    'Select...',
    '16:9 (HD/Standard)',
    '2.39:1 (Cinemascope)',
    '1.85:1 (Theatrical)',
    '4:3 (Classic TV)',
    '1:1 (Square)',
    '9:16 (Vertical/Mobile)',
    '21:9 (Ultra Wide)',
  ],
  lighting: [
    'Select...',
    'Natural Light',
    'Key Light',
    'Fill Light',
    'Back Light',
    'Three-Point Lighting',
    'High Key',
    'Low Key',
    'Practical',
    'Hard Light',
    'Soft Light',
    'Motivated',
    'Silhouette',
    'Chiaroscuro',
  ],
  mood: [
    'Select...',
    'Neutral',
    'Happy / Joyful',
    'Sad / Melancholic',
    'Tense / Suspenseful',
    'Romantic',
    'Dark / Ominous',
    'Bright / Optimistic',
    'Mysterious',
    'Dramatic',
    'Calm / Peaceful',
    'Chaotic',
    'Intimate',
  ],
};

export const SHOT_LIST_HEADERS = [
  '#',
  'Scene',
  'Shot Size',
  'Perspective',
  'Movement',
  'Equipment',
  'Focal Length',
  'Aspect Ratio',
  'Lighting',
  'Mood',
  'Description',
  'Duration',
  'Notes',
];

